### ISSUE TITLE
Unable to deploy docker artifact from ECR repository

### ISSUE THREAD

**Issue by danimorelo** [nimakaviani/managed-delivery-k8s-plugin#101]
Unsure if this would be a feature request or a bug. Haven't seen examples for this specific case, only for docker hub artifacts.

Spinnaker version: 1.26.6
Plugin version:       0.0.6
Keel version: 
```
- name: us-docker.pkg.dev/spinnaker-community/docker/keel:spinnaker-master-latest-unvalidated
  newTag: 0.1.0-20210420170214

```
Got keel to find a artifact version with a numbered tag to deploy with the following managed delivery config:
```
...
artifacts:
- name: myapp
  type: docker
  reference: my-ecr-artifact2
  tagVersionStrategy: semver-tag
...

```
Then setting spec.conatiner and image to that ref my-ecr-artifact2 imports md config successfully and attempts to deploy the Deployment resource. 
Unfortunately the image inferred by the reference looks as the following and K8s fails to pull the image
`Back-off pulling image "myapp/myapp:4162029"`

Being an ECR repo I would expect the image to be resolved as: 
`<AWS_ACCT>.dkr.ecr.<Region>.amazonaws.com/myapp:4162029
`
I see that info is present when searching in clouddriver (dockerRegistry/images/find?) so it so close to working but Keel doesn't seem to put it together.
Is there somewhere I am missing to configure this properly or ECR repo isn't currently supported.

Thank you for this great plugin,
BR
Daniel

**Comment by nimakaviani** [comment]
Thank you for raising the issue. Let us look into it and see if we can reproduce it.

/cc @nabuskey

**Comment by nabuskey** [comment]
I think this was an issue with the way FQDN docker images are resolved in older version of keel. The version of keel you are using seems to be an old one before the fix was applied to keel. Unfortunately I couldn't get Keel build process to push container images automatically but I did push newer images to an ECR repo. 
See if you can use the latest image version available here: https://gallery.ecr.aws/q1x7y7f4/spinnaker-keel

**Comment by danimorelo** [comment]
Thank you for the quick response :) giving a try to that version

**Comment by danimorelo** [comment]
Seems to start keel service and then crash with this:

```2022-01-04 21:41:43.124  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : default - Start completed.
2022-01-04 21:41:46.415  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'keelConfigurationFinalizer' defined in URL [jar:file:/opt/keel/lib/keel-web.jar!/com/netflix/spinnaker/config/KeelConfigurationFinalizer.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.amazon.spinnaker.keel.k8s.resolver.K8sResourceHandler': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.amazon.spinnaker.keel.k8s.resolver.GenericK8sResourceHandler] from ClassLoader [org.pf4j.PluginClassLoader@50f71f48]```

Might need to upgrade plugin version as well?

**Comment by danimorelo** [comment]
Now failing just a bit before deployment because it is searching in the wrong docker registry:

`2022-01-04 21:58:26.778  INFO 1 --- [driver:7002/...] okhttp3.OkHttpClient                     : <-- 200 http://clouddriver:7002/dockerRegistry/images/find?account=deploy-keel-registry&repository=inform-wsm-dashboard&tag=4162029 (29ms, 113956-byte body)
2022-01-04 21:58:26.783  WARN 1 --- [atcher-worker-3] c.n.s.keel.actuation.ResourceActuator    : Resource check for k8s:resource:deploy-keel-keel-deployment-wsm-dashboard failed (hopefully temporarily) due to No Docker image found for inform-wsm-dashboard:4162029 in deploy-keel-registry`

I have 2 registry defined, that one deploy-keel-registry for docker hub and the second i would expect here for ECR. Also the ECR one is set as the primary.

```  dockerRegistry:
    enabled: true
    accounts: 
    - address: https://index.docker.io
      cacheIntervalSeconds: 30
      cacheThreads: 1
      clientTimeoutMillis: 60000
      email: fake.email@spinnaker.io
      insecureRegistry: false
      name: deploy-keel-registry
      paginateSize: 100
      permissions: {}
      repositories:
      - library/nginx
      sortTagsByDate: false
      trackDigests: false
    - name: my-ecr-registry
      requiredGroupMembership: []
      permissions: {}
      address: https://**.dkr.ecr.us-east-1.amazonaws.com
      username: AWS
      passwordCommand: aws --region us-east-1 ecr get-authorization-token --output text
        --query 'authorizationData[].authorizationToken' | base64 -d | sed 's/^AWS://'
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories: []
    primaryAccount: my-ecr-registry
```

**Comment by danimorelo** [comment]
Figured the registry name has to match the account srt in managed delivery config as follows:

registry_name = account_name-registry

After renaming my second registry to match the account it worked properly, thank you!

Is there another way to set the registry name or they must always match like this? thinking that then will have to set multiple copies of the same ECR registry to match multiple environments to deploy to.

**Comment by nabuskey** [comment]
That was the behaviour prior to version `0.0.11`. If you are using keel version `203+` and plugin version `0.0.11+`, you shouldn't have ran in to the problem. 
https://github.com/spinnaker/keel/pull/1999
https://github.com/nimakaviani/managed-delivery-k8s-plugin/pull/97
I think the reason you are running into it because you had an older version of keel and plugin before.  Docker artifact version was stored without required metadata in it. So you could push a new version of docker image to ECR, deregister the artifact, or drop everything in the DB and start fresh.

**Comment by danimorelo** [comment]
Still encountering the issue after pushing new versions to ECR and trying to create a new spinnaker application.
Can see in artifacts DB as the metadata is now populated with the appropriate registry
```
mysql> select * from artifact_versions;
+----------------------+--------+---------+----------------+------------+----------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------+
| name                 | type   | version | release_status | created_at | build_metadata | git_metadata | original_metadata                                                                                                                      |
+----------------------+--------+---------+----------------+------------+----------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------+
| myapp                | docker | 4162029 | NULL           | NULL       | NULL           | NULL         | NULL                                                                                                                                   |
| myapp                | docker | 4162030 | NULL           | NULL       | NULL           | NULL         | {"tag": "4162030", "fullname": "myapp:4162030", "registry": "fq-dev-registry"}                                          |
| myapp                | docker | 4162031 | NULL           | NULL       | NULL           | NULL         | {"tag": "4162031", "fullname": "myapp:4162031", "registry": "fq-dev-registry"}                                          |
| library/nginx        | docker | 1.21.4  | NULL           | NULL       | NULL           | NULL         | NULL                                                                                                                                   |
| library/nginx        | docker | 1.21.5  | NULL           | NULL       | NULL           | NULL         | {"registry": "index.docker.io", "fullImagePath": "index.docker.io/library/nginx:1.21.5", "clouddriverAccount": "deploy-keel-registry"} |
+----------------------+--------+---------+----------------+------------+----------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------+
```
But when deploy reaches the second environment called deploy-keel, it still tries to find the image deploy-keel-registry:

```
2022-01-05 20:50:10.476  INFO 1 --- [driver:7002/...] okhttp3.OkHttpClient                     : <-- 200 http://clouddriver:7002/dockerRegistry/images/find?account=deploy-keel-registry&repository=inform-wsm-dashboard&tag=4162031 (162ms, 113956-byte body)
2022-01-05 20:50:10.484  WARN 1 --- [atcher-worker-6] c.n.s.keel.actuation.ResourceActuator    : Resource check for k8s:resource:deploy-keel-keel-deployment-wsm-dashboard failed (hopefully temporarily) due to No Docker image found for inform-wsm-dashboard:4162031 in deploy-keel-registry
```

Is artifact_versions the DB I should be dropping to start fresh?

Thank you

**Comment by nabuskey** [comment]
So in the table you can see that `library/nginx:1.21.5` was filled after the keel version was updated because `fullImagePath` field is present within its metadata. 
In the log, you can see that it's attempting to pull `inform-wsm-dashboard:4162031`. However, this does not have the `fullImagePath` field in its metadta. 
I think the easiest path to test your use case is:  
1. Scale keel down to 0. `kubectl -n <NS> scale deployment keel --replicas 0`
2. Connect to your mysql instance and drop the database. `DROP DATABASE keel` then `CREATE DATABASE keel` 
3. Scale up keel. `kubectl -n <NS> scale deployment keel --replicas 1`

This seems extreme but it's likely the easiest path for you to get it working. You can also delete the delivery config or push a new version of `inform-wsm-dashboard `, I believe. But I would start fresh.

**Comment by danimorelo** [comment]
Worked beautifully. Still at early stages so no issue dropping whatever is needed ^^
Thanks again
