### ISSUE TITLE
rootProject.version is probably needed for other versioning reasons

### ISSUE THREAD

**Issue by nimakaviani** [nimakaviani/managed-delivery-k8s-plugin#18]
We removed `rootProject.version` in [this PR](https://github.com/nimakaviani/managed-delivery-k8s-plugin/pull/16/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19L2) but it looks like there are a couple of places like here https://github.com/nimakaviani/managed-delivery-k8s-plugin/blob/master/build.gradle#L37

and here https://github.com/nimakaviani/managed-delivery-k8s-plugin/blob/master/build.gradle#L44

that we need `rootProject.version`. Can we safely get rid of these instances or should we in fact put the version back as part of the build process.

/cc @nabuskey

**Comment by nabuskey** [comment]
Should be okay. Same things are done here and no version is specified. : https://github.com/spinnaker-plugin-examples/springExamplePlugin/blob/master/build.gradle

As long as version is specified at release, there shouldn't be an issue. The bash one liner checks for presence (null or empty) of version variable before building as well.

**Comment by nimakaviani** [comment]
I see. I thought maybe what we have in build.gradle is used as lib metadata when the library is published to a maven repo, but not quite sure. could be a no issue.

**Comment by nimakaviani** [comment]
put it back in #35 ... turned out `./hack/build.sh` relied on this to produce the artifact. we should find a proper way to bump the version when we cut a new release.
