### ISSUE TITLE
Add support for constrains

### ISSUE THREAD

**Issue by nabuskey** [nimakaviani/managed-delivery-k8s-plugin#20]
Constrains like manual approval do not seem to work for k8s resources. (depends works). 
We need to investigate.

**Comment by JonGilmore** [comment]
I don't know if this is still an issue. I was able to get the following to work just fine when testing the plugin:

```
    constraints:
      - type: manual-judgement
        timeout: P5D
```

**Comment by nimakaviani** [comment]
yeah I think this was an issue with an older version of deck, but no more.
