### ISSUE TITLE
k8s job name special characters

### ISSUE THREAD

**Issue by JonGilmore** [nimakaviani/managed-delivery-k8s-plugin#95]
Currently, if there is a special character (such as a `~`) in the app version, the k8s job will blow up. This can be resolved by simply replacing tilde's with dashes both [here](https://github.com/nimakaviani/managed-delivery-k8s-plugin/blob/277de3f51aad2d4175d9d99d2b649443880898df/k8s-plugin-keel/src/main/kotlin/com/amazon/spinnaker/keel/k8s/verificationEvaluator/K8sJobEvaluator.kt#L136) and [here](https://github.com/nimakaviani/managed-delivery-k8s-plugin/blob/277de3f51aad2d4175d9d99d2b649443880898df/k8s-plugin-keel/src/main/kotlin/com/amazon/spinnaker/keel/k8s/verificationEvaluator/K8sJobEvaluator.kt#L176). But, I'm not sure that's the best solution in the long term (for example, if you try to lookup this later w/ the modified name, will this break other things?). Anybody using Nebula will run into this issue. Hoping we can at least start up a discussion here to figure out what the best approach is to fixing this. 

Here's the error you'll receive from the broken task if you have a tilde: 
```
Exception: Create failed: The Job "verify-appname-dev-appname-0.1041.0~dev.2-h2210.f1zv5dj" is invalid: * metadata.generateName: Invalid value: "verify-appname-dev-appname-0.1041.0~dev.2-h2210.f1f1088": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') * metadata.name: Invalid value: "verify-appname-dev-appname-0.1041.0~dev.2-h2210.f1zv5dj": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') * metadata.labels: Invalid value: "appname-0.1041.0~dev.2-h2210.f1f1088": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') * spec.template.labels: Invalid value: "verify-appname-dev-appname-0.1041.0~dev.2-h2210.f1zv5dj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

Thanks!

**Comment by nimakaviani** [comment]
so for me to understand the problem, you have your artifact version as the following, right? `0.1041.0~dev.2`

and then what would be the next version? something like `0.1041.0~dev.3`?

You mentioned this is a constraint with Nebula. Can you help me understand how? Never worked with Nebula before, so any insight as to why there needs to be a `~` helps.

my first impression, I'd say artifact handlers should prevent resource versions from having any special characters in their names or version so we dont have to care about special characters them down the chain.

It is going to get complicated and error-prone if we try to whitelist special characters, so my gut feeling is that we should adhere to the same naming conventions enforced by k8s for labels and annotations also. example here: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set 

unless there are really strong arguments against it.

**Comment by JonGilmore** [comment]
So, in this case, the appVersion is actually `0.1041.0~dev.2-h2210.f1zv5dj`. Nebula versioning (more info [here](https://nebula-plugins.github.io/)) will output `0.1041.0~dev.2`, then the `h2210` is the build number and `f1zv5dj` is the short sha. 

>my first impression, I'd say artifact handlers should prevent resource versions from having any special characters in their names or version so we dont have to care about special characters down the chain.

Unfortunately, I don't think your first impression is going to work, the way that keel works with debs is that it makes a whole bunch of assumptions about versioning. You can see Netflix already does a similar replace in the [ImageService](https://github.com/spinnaker/keel/blob/7065b7860e90d69c06243caf1adb7e49190edd23/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/ImageService.kt#L100). Might be nice to see if @luispollo could chime in on this to get his opinion though. 

> It is going to get complicated and error-prone if we try to whitelist special characters

Agreed, unfortunately I'm not sure what the best resolution for this would be 🤔 
Appreciate the conversation on this, thanks!
